theme = "dracula"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
true-color = true
auto-format = false # Ruff does this weird thing when I save file again, destroys everything

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-s = ":w"
"C-/"= "toggle_comments"

[keys.normal.space]
q = {q = ":q"}

[keys.insert]
"C-/"= "toggle_comments"
