theme = "everforest_dark"

[editor]
line-number = "relative"
bufferline = "always"
color-modes = true
true-color = true
auto-format = false # Ruff does this weird thing when I save file again, destroys everything
cursorline = true
rulers = [120]

[editor.indent-guides]
character = "╎"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[keys.normal]
C-s = ":w"
"C-/"= "toggle_comments"

"C-space"= "completion"

[keys.normal.space]
q = {q = ":q"}
b = {q = ":buffer-close", d = ":buffer-close"}

[keys.insert]
"C-/"= "toggle_comments"
C-s = ":w"
"C-space"= "completion"

[keys.normal.g]
b = "buffer_picker"
